#端口配置
server:
  port: 8002
#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  devtools: #热部署生效
    restart:
      enabled: true
      additional-paths: src/main/java  #设置重启的目录,添加那个目录的文件需要restart
mybatis:
  type-aliases-package: com.wang.dto
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: MYSQL